### ISSUE TITLE
set temperature not working

### ISSUE THREAD

**Issue by pmonday** [zpriddy/ZP_EchoNestPy#6]
I wandered through the installation and I can get some information from my nest but I've noticed that the change in temperature is not working (set temperature to 71).  There is an invalid content message returned (see below).  I've also noticed that the control requests (turn up the nest) don't have an effect.  My app permissions are r/w for the thermostat at nest.com ... hmmm, any other thoughts?

<Response [400]>
{"error":"Invalid content sent","type":"https://developer.nest.com/documentation/cloud/error-messages#invalid-content-sent","message":"Invalid content sent","instance":"ec1ead33-e3cc-4326-908e-0b45226d0907"}

The Amazon service receives a good response:
{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "type": "PlainText",
      "text": "Setting Nest to 71 degrees fahrenheit"
    },
    "card": {
      "type": "Simple",
      "content": "Telling Nest to set to 71 degrees fahrenheit.",
      "title": "Nest Control - Setting Nest Temp"
    },
    "reprompt": null,
    "shouldEndSession": true
  },
  "sessionAttributes": null
}

**Comment by pmonday** [comment]
Strange, I had to change setTemperatureAll

The command_uri has to have target_temperature_f in it and the body just contains the target temperature as a string.  Could my account be defaulting to an incorrect version of the Nest API perhaps?

```
#command = {"target_temperature_f":int(temp)}
command = str(temp)

commandSucessfull = True


for device in thermostats:
    print "Device:" + device
    #command_uri = 'https://developer-api.nest.com/devices/thermostats/' + device + "?auth=" + token
    command_uri = 'https://developer-api.nest.com/devices/thermostats/' + device + "/target_temperature_f?auth=" + token
```

**Comment by zpriddy** [comment]
It could be. I havent touch it in a while and I believe that they may have changed the API. When did you create your nest account?

**Comment by zpriddy** [comment]
This will also have to be applied to http://github.com/zpriddy/ZP_EchoSmartThingsPy
